### PR TITLE
lispy-occur is in its own file

### PR DESCRIPTION
**Pull request by aaronjensen**
Ensures that swiper and ivy only load on demand.

@abo-abo I'm not sure if you'd like this, but it helps work around some of the issue of #610. It will still require and load swiper/ivy as needed. The only exception is one call to `ivy--get-window`. Because that is not an autoload function, it will fail if ivy isn't loaded explicitly. A require could be added there, but I'm not sure that's the best approach.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks, merged. See also the follow-up commit.

**Comment by aaronjensen** [comment]
That’s great, thanks. Is the manual auto load necessary for cases where people do not generate an auto load file? That’s an area of emacs that is a mystery to me because straight.el just does it all for me.

**Comment by aaronjensen** [comment]
Also should there be an auto load declaration for ivy-read?

**Comment by abo-abo** [comment]
`ivy-read` is already autoloaded. The manual autoload is necessary because below we have:

```elisp
(lispy-define-key map "y" 'lispy-occur)
```

**Pull request closed without merging**
