### PR TITLE
Add failing tests for lispy-paredit-delete fns

### PR DESCRIPTION
**Pull request by sooheon**
Progress on #68.

Reopening after accidentally writing over last PR. git-reflog is awesome!

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks, I'm glad you didn't lose your work:)

**Comment by sooheon** [comment]
BTW was this intended behaviour for delete?

```
(foo
    |bar)
```

Gives:

```
(foo |bar)
```

Note the misindentation. I think the first delete should correct misindentation, and the next should join lines, and it's thrown me off a couple of times.

**Comment by abo-abo** [comment]
> was this intended behaviour for delete?

Which command are you talking about?

**Comment by sooheon** [comment]
Ah sorry: `lispy-delete-backward`, same behaviour for `lisps-backward-delete` as well, as it's built off it.

**Comment by abo-abo** [comment]
Thanks. Merged and fixed. I've updated two tests, please review the referenced commit.

**Pull request closed without merging**
