### PR TITLE
lispy.el: Add lispy-slurp-or-barf functions

### PR DESCRIPTION
**Pull request by sooheon**
Implements #199. <> keys in special will function as if they are moving the
delimiter at point in the specified direction, rather than always
slurping or always barfing.

### CODE REVIEW

**Comment by abo-abo** [comment]
Could you make them reuse `lispy-slurp` and `lispy-barf`? Just check that point side and call one or the other.

And some tests would be nice as well.

**Comment by sooheon** [comment]
Ok, there was no reason to break apart the functions like that, thanks for the tip. For the tests, I see the second arg to `lispy-with` is often just the key (like ">")--is there a way to rebind the key within the scope of a test, or is it fine to just call the function manually as the second arg?

**Comment by abo-abo** [comment]
Yes, it's fine to call them as the second arg.

**Comment by sooheon** [comment]
I've added tests (from slurp and barf), but they could use review, I find it confusing to read the test strings.

**Comment by noctuid** [comment]
@sooheon It probably also makes sense to check the location of the point if the region is active like lispy-slurp does (e.g. `(= (point) (region-beginning))` will barf with `>` and slurp with `<`).

**Comment by abo-abo** [comment]
Looks good, thanks.

**Pull request closed without merging**
