### PR TITLE
Add case to lispy-delete-backward to deal with accidental comments

### PR DESCRIPTION
**Pull request by sooheon**
Addresses #329

One test is failing, I could use some help:

    (foo ;; |
    )

Leads to:

    (foo|
    )

I'd like to bring the closing paren up, but couldn't find a simple way to do it. I wish there was lispy--normalize-outer or something.

### CODE REVIEW

**Comment by sooheon** [comment]
Also, I'm getting the following error trying to run tests locally:

    D/c/e/lispy (delete-atom-from-within) $$ make all                   1m 22s 9ms
    emacs -batch -l elpa.el -l lispy-inline.el -l lispy.el -l targets/compile.el
    Cannot open load file: No such file or directory, avy
    make: *** [compile] Error 255

**Comment by noctuid** [comment]
@sooheon I may be wrong, but it sounds like you need to run `make cask` again.

**Comment by sooheon** [comment]
@noctuid weird, I tried that, and make tells me "make: Nothing to be done for `cask'."

**Comment by sooheon** [comment]
@noctuid weird, I tried that, and make tells me "make: Nothing to be done for `cask'."

**Comment by abo-abo** [comment]
This was changed a while ago. Use `make update` instead.

**Comment by sooheon** [comment]
Got it. Any tips on the lispy--normalize issue?

**Comment by abo-abo** [comment]
Step back out and call it.

**Comment by abo-abo** [comment]
Thanks.

**Pull request closed without merging**
