### PR TITLE
lispy-describe-inline restore window configuration

### PR DESCRIPTION
**Pull request by rcj**
In case the description is to long to show it in the inline overlay,
lispy-describe-inline calls describe-function/variable which shows the
documentation in an extra help window. However when calling
lispy-decribe-inline again to hide the documentation, the help window is
simply killed, destroying the previous window configuration.

If lispy-restore-windows is set to true, the window configuration will
be saved before the documentation is shown, and restored after it is
hidden again.

### CODE REVIEW

**Comment by abo-abo** [comment]
I made an alternative change that's supposed to fix the same issue. Please test.

**Comment by rcj** [comment]
Thank you, looks a lot cleaner. 

There is one minor problem. If you have only 2 windows open, the help window will cover the other window and the active window will remain the window lispy-describe-inline was called in. This is great as you can read the doc and close it directly again. However if you have more than two windows open, it will pick one too show the help window (which might be too small, so same problem as with the inline overlay) and in addition the help window will be the active window. This is now inconsistent with the case where we have only two windows. For two windows I have to hit C-1 again to close the documentation and for 3+ windows I have to use 'q'.

Thanks for the great work!

**Comment by abo-abo** [comment]
> and in addition the help window will be the active window

This isn't what I see on my end: for 3 windows the help window will occupy one of them, but it will not be active.
Please check if everything was updated, and maybe also with `emacs -Q`.

**Comment by rcj** [comment]
I just checked with emacs -Q to be sure in the following three constellations:
Mac OS X Emacs Version 24.5.1 in terminal and gui mode
Archlinux Emacs Version 24.5.1 in terminal

If I have the following window configuration (* = cursor position)

-----------------------------------
| *(define-key)  |   xxxxxxx |
|                       |                 |
|-------------------|                 |  
| yyyyyyyyyyy  |                 |
|                       |                 |
------------------------------------

and the help window pops up in the bottom left window, the bottom left window will also be the active window.

Then I built current HEAD and there the cursor stays in the source window. So it seems this problem is fixed in Emacs 25. That is good enough for me.

**Comment by abo-abo** [comment]
Thanks for checking, it should work for emacs24 as well now.

**Comment by rcj** [comment]
Looks good, thanks!

**Pull request closed without merging**
