### PR TITLE
Update docs for lispy-slurp and lispy-pair

### PR DESCRIPTION
**Pull request by noctuid**
This addresses #229. 

I followed the instructions, and the documentation generally looks the same. However, the syntax higlighting colors are different except for in `lispy-describe-inline` and `lispy-arglist-inline` (the colors are specified in the org file). What should I do about that?

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks.

> What should I do about that?

The way it looks depends on the theme used by `emacs -Q`. 

    (add-to-list 'load-path "../../eclipse-theme")
    
Just clone `eclipse-theme` to be in the same directory as `lispy`, and the syntax highlighting on export will be the same as mine.

**Comment by noctuid** [comment]
My bad; I should have looked closer at the changes. Why is it `../../` as opposed to `../`? I had to put everything two directories back instead of in the same directory as the lispy folder.

**Comment by abo-abo** [comment]
Oh right. I have the following folder structure:

    ./git/lispy/.git
    ./git/lispy/gh-pages/.git
    
I cloned the `gh-pages` as an orphan branch into its own repository *inside* the lispy git repository folder.  And I made Git ignore the `gh-pages` folder.

Also:

    ./git/lispy/wiki/.git
    
because why not? :)

**Comment by noctuid** [comment]
Thanks, that makes sense. Would it be okay to add a `.gitignore` to the repo?

**Comment by abo-abo** [comment]
OK.

**Comment by noctuid** [comment]
I don't know why I didn't notice that there already is one. Sorry about that.

**Pull request closed without merging**
