### PR TITLE
Add extra arguments and behavior for lispy-pair

### PR DESCRIPTION
**Pull request by noctuid**
With this all the functionality mentioned in #197 is implemented. I changed lispy-pair to use the raw prefix arg so no arg and an arg of 1 can be distinguished between. `M-1 (` now behaves as `M-2 (`, so the documentation for lispy-pair will need to be updated if this is merged.

Also, I think it would be nice if there was some way to choose whether or not to insert a space after wrapping. This is definitely useful in some cases, but I think I'd find it more useful if it wasn't the default. Maybe an option could be added to control the default. I was also thinking it might make sense to do something like temporarily bind space to insert a space after the point after wrapping if the point wasn't already in special. Maybe a hydra with `:foreign-keys run` and `:exit t` could be used for this. So for example:

```
|a
;; "M-1 (" gives this; no space by default
(|a)
;; pressing space gives this
(| a)
```

What do you think? I could change this pull request or make a new one with an option for this if you like the idea.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks. Could you leave for me <kbd>C-u (</kbd> to do the previous thing? I'm too used to having it work that way. And it's probably rare for someone to want to wrap exactly 4 sexps.

Also keep in mind https://github.com/abo-abo/lispy/blob/gh-pages/index.org. At some point it should be updated with the new stuff.

**Comment by noctuid** [comment]
Okay I've made it so `C-u` will act the same as `M-1`.

Yes, I can make a pull request to update the documentation as well.

What did you think about my suggestion? Would you accept a pull request for that hydra? If you would, should the default behavior be to always insert a space after wrapping instead of using the hydra?

**Comment by abo-abo** [comment]
> If you would, should the default behavior be to always insert a space after wrapping instead of using the hydra?

This seems like a good behavior. Should `lispy-space` be wired to do this always, even not after a wrap?

**Comment by noctuid** [comment]
Do you mean it should always insert a space after the point when `(looking-back lispy-left)` instead of just in the "jammed" situation? Yeah, I think that is a better idea. I can't think of a situation where it would be useful to have a space right after an opening delimiter.

Also, I noticed that `lispy-space`'s docstring says space with `(|(` will result in `( |(`. Shouldn't the point be before the space?

**Comment by abo-abo** [comment]
Yeah, that's a typo.

**Pull request closed without merging**
