### PR TITLE
Add failing tests for lispy-paredit-delete fns

### PR DESCRIPTION
**Pull request by sooheon**
Progress on #68.

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks for the work. I'll merge it when I get some time to make them not fail:)

**Comment by abo-abo** [comment]
Why close this? I thought there were some useful tests here.

**Comment by sooheon** [comment]
I think I fucked up with git, this was on master of my fork instead of its own branch, and I force pushed onto it.

**Comment by abo-abo** [comment]
> don't seem to have this checked out anywhere else, I guess it's gone for good :( Lesson learned...

Try looking in the reflog. The reflog on my machine has 1000 saved positions, unfortunately your commit isn't there.  I'll have to check on my other laptop as well, see if I can recover it.

Here's what you can try:

    git reflog > reflog.txt
    
and search `reflog.txt` for `Add failing tests...`.

**Pull request closed without merging**
