### PR TITLE
Improve lispy-comment

### PR DESCRIPTION
**Pull request by nnoodle**
Makes inserting subsequent `;` after `;; ` add another semicolon `;;; `, except when in emacs-lisp-mode, where inserting `;` after `;;; ` will add the autoload cookie.

### CODE REVIEW

**Comment by abo-abo** [comment]
What's the use case of inserting e.g. `;;; foobar` in Elisp?

**Comment by nnoodle** [comment]
Specifically for Elisp, it's for writing the header/footer lines, and the Commentary/Code sections in the header.

**Comment by abo-abo** [comment]
Thanks. I fixed the failing tests. Please use `make test` to check if the tests pass next time.

**Comment by nnoodle** [comment]
Thanks! Will do.

**Pull request closed without merging**
