### PR TITLE
Improve delete-or-splice-or-slurp commands

### PR DESCRIPTION
**Pull request by noctuid**
This implements the suggested behavior from #230.

### CODE REVIEW

**Comment by abo-abo** [comment]
> (should (string= (lispy-with "\"a b c\"|" (kbd "DEL")) "\"a b c|\""))

I disagree with this for the main `lispy` code - strings can be seen as either lists or delimited atoms, I think it makes sense to delete the whole thing with <kbd>DEL</kbd> in both cases.  Otherwise, the user might expect <kbd>DEL</kbd> to not delete in other cases.

I can still merge this into the Parinfer part. Could you just think again if it's the right behavior? Is there a good example for when this is useful?

**Comment by noctuid** [comment]
> I disagree with this for the main lispy code 

I do as well. Just to clarify, I only changed the behavior for the parinfer commands. There's not really a way to handle strings that is consistent with parinfer's behavior for lists since splicing and slurping aren't really useful for strings. Parinfer doesn't even bother trying to do anything special with quotes; it just deletes them one by one. I didn't really like that idea, so originally I just had the commands behave the same as the lispy equivalents.

>Is there a good example for when this is useful?

I think it's more consistent with how the parinfer theme's `DEL` behaves for lists. `DEL` after a list will move the point backward when unable to slurp further. @sooheon suggested this change and may want to weigh in further.

**Comment by sooheon** [comment]
Yeah, in main lispy `lispy-delete-backward` will delete lists and entire quotes at once. In parinfer, del is not quite so destructive, and a single del never deletes entire expressions, so deleting the whole quote feels out of place. Del moves through the closing delimiter, displacing it when slurping is appropriate, or just moving the point. This is pretty much how paredit delete works as well.

**Comment by abo-abo** [comment]
Thanks.

**Pull request closed without merging**
